### ISSUE TITLE
Finagg install issues

### ISSUE THREAD

**Issue by Mason-0001** [theOGognf/finagg#45]
Using finagg install on a mac, python 3.10.4 using pyenv and I am running into this error when using "finagg install":

Traceback (most recent call last):       sqlite3.OperationalError: no such table: sec.raw.submissions

Is there any fix to this?

**Comment by theOGognf** [comment]
Which version of finagg are you using @Mason-0001?

**Comment by Mason-0001** [comment]
Name: finagg
Version: 0.0.0b1
I went with the stable version using pip install.

**Comment by theOGognf** [comment]
@Mason-0001 I believe you likely forgot to specify a ticker set option (`--ticker-set`/`-ts`) when installing via `finagg install`. The ticker set option specifies which tickers to install data for. Since no option was provided, the SEC install was skipped, but the fundam installation continued. The fundam installation then tried reading from the SEC table, resulting in the operational error because no data was downloaded to create the table in the first place

Please verify if this is the case and I'll be sure to put in a fix on the main branch

**Comment by theOGognf** [comment]
@Mason-0001 https://github.com/theOGognf/finagg/pull/46 this should cover what you encountered. I'll merge when you confirm this was the issue or in 2 days, whichever comes sooner

**Comment by Mason-0001** [comment]
That solved the problem, my mistake.

Thanks

**Comment by theOGognf** [comment]
No worries - thanks for the issue. It led to some improvements. #46 was merged in
