### ISSUE TITLE
financial statements do not match

### ISSUE THREAD

**Issue by jegauth** [theOGognf/finagg#54]
Hello theOGognf! I have a little question for you. When I go on quickfs.net or Seeking Alpha I got these result for the gross profit for AAPL: 

![image](https://github.com/theOGognf/finagg/assets/116890061/533d0636-258c-4b49-a19f-8f1871a6f3dc)

When I use your code

```
df = finagg.sec.api.company_facts.get(ticker="AAPL")  # get all data associated with AAPL
df = finagg.sec.api.get_unique_filings(df, form="10-K")  # get all unique annual filings
df = finagg.sec.api.join_filings(df, form="10-K")  # pivot the table for convenience
```
I got this result

![image](https://github.com/theOGognf/finagg/assets/116890061/37e30bc7-dfb0-4fee-9538-b3bbd9a18322)

Just one example, look at the gross profit in FY 2023, i.e. 1.5283e+11, and look where it is located in the spreadsheet. The same result is located in year 2021. So it is delayed by almost 2 years. Is it normal? There might be an issue somewhere. Can you look at it

**Comment by theOGognf** [comment]
@jegauth This is a good issue. I did some digging; **this is a bug from my misunderstanding of the usage of the "start", "end", "filed", "fy", "fp", and "frame" columns**.

I assumed "fy" corresponded to the fiscal year that a filing was for, but it is in fact the fiscal year that the filing was submitted (the data could be for a prior fiscal year, and, in Apple's case, they seem to resubmit filings each year for filings 2 years prior pretty consistently). It seems "filed", "fp", and "frame" all follow the same convention (and in "frame"'s case, is NaN a good bit of the time).

This makes it a bit tricky, because now I must find a new method to determine which fiscal period/frame a filing is actually for instead of relying on the provided columns. This isn't hard to do, but just requires some extra work to guarantee I'm not including data from other quarters or years, since it seems like not all filings are cleanly separated by quarters/years

Thanks for submitting this issue. I probably won't have a lot of time this weekend to work on a solution, but I will work on this when I get a chance. A conservative estimate for an implemented fix from me is probably ~4wks from now

**Comment by jegauth** [comment]
To be honest, you are not that far from delivering a very good repo!! It saved me a lot of time. Can I pay you something so that you can fix it up sooner? I will also try to fix it up

**Comment by theOGognf** [comment]
> To be honest, you are not that far from delivering a very good repo!! It saved me a lot of time. Can I pay you something so that you can fix it up sooner? I will also try to fix it up

Haha no, that's alright. You're more than welcome to try to fix it yourself - I'll happily review your PR

You just need to update the `finagg.sec.api.get_unique_filings` and `finagg.sec.api.join_filings` methods to use the `"start"` and `"end"` columns to separate filings by their correct quarters instead of using the given `"fy"` and `"fp"` columns. There should be a filing with a `"filed"` column that's 30-90days after the `"end"` date for the first filing of each year/quarter, which should be a good thing to validate against. We probably also want to keep the same indexing convention (using `"fy"`, `"fp"`, and `"filed"` for indices, but overwriting `"fy"` and `"fp"` with the correct year and quarter, respectively)

**Comment by jegauth** [comment]
![image](https://github.com/theOGognf/finagg/assets/116890061/8b633d8c-b9bd-4167-af48-14d513a025f4)

We can see that the error might be located here: `df = finagg.sec.api.company_facts.get(ticker="AAPL")`

**Comment by jegauth** [comment]
![image](https://github.com/theOGognf/finagg/assets/116890061/a0280fa8-51c5-4a4f-912b-f4f9e42f188f)
Can you see the error?

**Comment by jegauth** [comment]
It seems to be fixed. 

Here is my output: 
![image](https://github.com/theOGognf/finagg/assets/116890061/93ccd290-dd65-4af8-879c-94473ba9d250)

Here is the output from Seeking Alpha: 
![image](https://github.com/theOGognf/finagg/assets/116890061/717b3288-f3bc-40d2-aa13-ffc4b071699a)

Here is the part I fixed: 
![image](https://github.com/theOGognf/finagg/assets/116890061/1f10cef4-b252-4a98-85db-d6c7b1a65c36)

You can add those two lines in sec.api. Hope it helps!

**Comment by theOGognf** [comment]
Hey @jegauth ! Thanks again for finding this issue, reporting it, and getting a first-pass solution out for it. This really helped narrow down the issue and made it significantly quicker for me to put out a bugfix

I pushed an update to the main branch. If you can clone it and test it out, it should be more aligned to what we're expecting

**Comment by jegauth** [comment]
Hello @theOGognf! It seems we have the same issue again. Check it out because I have the same issue as before

**Comment by theOGognf** [comment]
> Hello @theOGognf! It seems we have the same issue again. Check it out because I have the same issue as before

Are you sure? Did you pull and reinstall like:

```bash
git pull
pip install .
```

**Comment by jegauth** [comment]
Yes, I did. I am pretty sure it is not working as expected. 

```
df = finagg.sec.api.company_facts.get(ticker="AAPL")  # get all data associated with AAPL
df = finagg.sec.api.get_unique_filings(df, form="10-K")  # get all unique annual filings
df = finagg.sec.api.join_filings(df, form="10-K")  # pivot the table for convenience
```

This code does not work as expected.

**Comment by theOGognf** [comment]
I can't seem to replicate the issue anymore while on the latest main branch on GitHub. Closing for now. Feel free to reopen an issue if you're unable to get the latest fix for it
