### ISSUE TITLE
Different tag for each company

### ISSUE THREAD

**Issue by jegauth** [theOGognf/finagg#55]
Hello! When I pull data in a dataframe from finagg, the total amortization and depreciation seems to have a different tag from one company to another. So it is hard to get their financial statements as Seeking Alpha or QuickFS would do. It is important for me to get for instance the capital expenditure, the D&A, etc similar to what I would get from Seeking Alpha or QuickFS. Can you help me with that?

I give you an example. For MSFT, the tag for the Depreciation and Amortization is this one 
![image](https://github.com/theOGognf/finagg/assets/116890061/4ada5607-6f00-48fa-b7a8-3f949470e5f5)

but from the url from your code, https://data.sec.gov/api/xbrl/companyfacts/CIK0000789019.json, there is no such tag. It becomes hard to get nice, well structured financial statements in a database.

**Comment by theOGognf** [comment]
Hey @jegauth, this is one of those issues focused on wrangling XBRL data / SEC filings. There's not a lot of standardization around how companies are allowed to publish their data, so folks actually put a great deal of effort into figuring out which tag for Company A corresponds to which tag for Company B. Folks also try to make up their own tags to standardize filings as well. There's not much I can help with here as it's a bit intractable to do this in the scope of this project

However, if you find that some data for a company is incorrect and it's potentially due to an implementation/bug in finagg, feel free to open another issue
